spring:
application:
name: notifshot

datasource:
url: jdbc:postgresql://localhost:5432/notifshot
username: postgres
password: postgres
driver-class-name: org.postgresql.Driver

jpa:
hibernate:
ddl-auto: validate
show-sql: false
properties:
hibernate:
dialect: org.hibernate.dialect.PostgreSQLDialect
format_sql: true

flyway:
enabled: true
baseline-on-migrate: true

kafka:
bootstrap-servers: localhost:9092
consumer:
group-id: notifshot-consumer
auto-offset-reset: earliest

redis:
host: localhost
port: 6379

server:
port: 8080

# Logging
logging:
level:
com.ilham: DEBUG
org.springframework.web: INFO
org.flywaydb: INFO
pattern:
console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Actuator
management:
endpoints:
web:
exposure:
include: health,info,prometheus,metrics
endpoint:
health:
show-details: always